[project]
name = "alma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.121.1",
    "itsdangerous>=2.2.0",
    "python-frontmatter>=1.1.0",
    "python-slugify>=8.0.4",
]
